contact/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('contact/', views.ContactView.as_view(), name='contact'),
]

menu/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.MenuListView.as_view(), name='home'),
]

reservation/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('reservation/', views.ReservationView.as_view(), name='reservation'),
    path('edit_reservation/',
         views.EditReservationView.as_view(), name='edit_reservation'),
]

thesavoryspot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("menu.urls"), name="menu-urls"),
    path("accounts/", include("allauth.urls")),
    path("accounts/signup/", include("allauth.urls")),
    path("", include("contact.urls"), name="contact-urls"),
    path("", include("reservation.urls")),
]

menu/models.py
from django.db import models


class Menu(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self):
        return self.title


class Category(models.Model):
    menus = models.ForeignKey(Menu, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Item(models.Model):
    categories = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return self.name

reservation/models.py
from django.db import models
from django.contrib.auth.models import User


class Year(models.Model):
    year = models.CharField(max_length=100)

    def __str__(self):
        return self.year


class Month(models.Model):
    years = models.ForeignKey(Year, on_delete=models.CASCADE)
    month = models.CharField(max_length=100)

    def __str__(self):
        return self.month


class Day(models.Model):
    months = models.ForeignKey(Month, on_delete=models.CASCADE)
    day = models.CharField(max_length=100)

    def __str__(self):
        return self.day


class Time(models.Model):
    days = models.ForeignKey(Day, on_delete=models.CASCADE)
    time = models.CharField(max_length=100)

    def __str__(self):
        return self.time


class Table(models.Model):
    times = models.ForeignKey(Time, on_delete=models.CASCADE)
    table = models.CharField(max_length=100)

    def __str__(self):
        return self.table


class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True,)
    year = models.ForeignKey(Year, on_delete=models.CASCADE)
    month = models.ForeignKey(Month, on_delete=models.CASCADE)
    day = models.ForeignKey(Day, on_delete=models.CASCADE)
    time = models.ForeignKey(Time, on_delete=models.CASCADE)
    table = models.ForeignKey(Table, on_delete=models.CASCADE)

    def __str__(self):
        return (
            f"DATE: {self.day} - {self.month} - {self.year} - "
            f"TIME: {self.time} - TABLE: {self.table} - USER: {self.user}"
        )

contact/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(
        max_length=100, label="Name", widget=forms.TextInput(attrs={
            'class': 'form-control', 'placeholder': 'Name'}))
    message = forms.CharField(
        widget=forms.Textarea(attrs={
            'rows': 5, 'class': 'form-control', 'placeholder': 'Message'}))

contact/views.py
from django.shortcuts import render, redirect
from django.views import View
import smtplib
import ssl
from email.message import EmailMessage
import os
from .forms import ContactForm


class ContactView(View):
    template_name = 'contact.html'
    form_class = ContactForm

    def get(self, request):
        form = self.form_class()
        sent = request.session.get('sent', False)
        request.session.pop('sent', None)
        return render(request, self.template_name, {
            "form": form, "sent": sent})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            message = form.cleaned_data['message']
            subject = 'Contact'
            body = f"""From {name}, username:{request.user}

            {message}"""

            email_sender = os.environ.get("email_sender")
            email_password = os.environ.get("email_password")
            email_receiver = os.environ.get("email_sender")

            em = EmailMessage()
            em['From'] = email_sender
            em['To'] = email_receiver
            em['Subject'] = subject
            em.set_content(body)

            context = ssl.create_default_context()

            with smtplib.SMTP_SSL(
                    'smtp.gmail.com', 465, context=context) as smtp:
                smtp.login(email_sender, email_password)
                smtp.sendmail(email_sender, email_receiver, em.as_string())
            request.session['sent'] = True
            return redirect("contact")
        return render(request, self.template_name, {"form": form})

reservation/views.py
from django.shortcuts import render, redirect
from .models import Year, Month, Day, Time, Table, Reservation
from django.views import View
from datetime import datetime
import smtplib
import ssl
from email.message import EmailMessage
import os


# Function to get context for rendering templates
def get_context(request):
    # Get current date and time information
    current_year = datetime.now().year
    current_month = datetime.now().month
    current_day = datetime.now().day
    current_hour = datetime.now().hour
    current_minute = datetime.now().minute
    current_time = current_hour + current_minute

    # Check session variables for reservation status
    reservation = request.session.get('reserved', False)
    request.session.pop('reserved', None)
    booked = request.session.get('booked', False)
    request.session.pop('booked', None)
    deleted = request.session.get('deleted', False)
    request.session.pop('deleted', None)

    # Get user reservations if user is authenticated
    user_reservations = ""
    if request.user.is_authenticated:
        user_reservations = Reservation.objects.filter(user=request.user)

    # Create context dictionary
    context = {
        'current_year': current_year,
        'current_month_range': range(current_month+1, 13),
        'current_month': current_month,
        'month_range': range(12),
        'current_day': current_day,
        'time_range': range(16, 21),
        'current_hour': current_hour,
        'current_hour_range': range(current_hour, 21),
        'current_minute': current_minute,
        'current_time': current_time,
        'reserved': reservation,
        'booked': booked,
        'deleted': deleted,
        'user_reservations': user_reservations,
    }
    return context


# Function to check existing reservations for a given date, time, and table
def check_existing_reservations(year_instance, month_instance, day_instance,
                                time_instance, table_instance):
    # Query the database for existing reservations
    existing_reservation = Reservation.objects.filter(
        year=year_instance,
        month=month_instance,
        day=day_instance,
        time=time_instance,
        table=table_instance,
    )
    return existing_reservation


def create(request):
    # Fetch email credentials from environment variables
    email_sender = os.environ.get("email_sender")
    email_password = os.environ.get("email_password")

    # Get the email of the requesting user
    email_receiver = request.user.email

    # Extract reservation details from the request
    year = request.POST.get('year')
    month = request.POST.get('month')

    # If month is not provided in the request, use the current month
    if month == "":
        month = request.POST.get('current_month')

    day = request.POST.get('day')
    time = request.POST.get('time')

    # If time is not provided in the request, use the current time
    if time == "":
        time = request.POST.get('current_time')

    # Get or create instances for Year, Month, Day, and Time
    year_instance, _ = Year.objects.get_or_create(year=year)
    month_instance, _ = Month.objects.get_or_create(
        years=year_instance, month=month)
    day_instance, _ = Day.objects.get_or_create(months=month_instance, day=day)
    time_instance, _ = Time.objects.get_or_create(days=day_instance, time=time)

    # Check the number of existing reservations for the given time slot
    existing_reservations_count = Reservation.objects.filter(
        year=year_instance,
        month=month_instance,
        day=day_instance,
        time=time_instance,
    ).count()

    # Set the maximum number of reservations allowed
    max_reservations = 3

    # If there is still space for reservations, create a new table instance
    if existing_reservations_count < max_reservations:
        table_instance, _ = Table.objects.get_or_create(
            times=time_instance, table=str(existing_reservations_count + 1))
    else:
        # If all slots are booked, set a flag in the session and return
        request.session['booked'] = True
        return False

    # Iterate over the possible table numbers and find the first available one
    for i in range(max_reservations):
        existing_reservation = check_existing_reservations(
            year_instance, month_instance,
            day_instance, time_instance, table_instance)
        if existing_reservation:
            table_instance, _ = Table.objects.get_or_create(
                times=time_instance, table=str(i + 1))

    # Create a new reservation instance
    reservation = Reservation.objects.create(
        year=year_instance,
        month=month_instance,
        day=day_instance,
        time=time_instance,
        table=table_instance,
        user=request.user
    )

    # Email confirmation details
    subject = 'Reservation'
    body = f"""Hello {request.user}

Thank you for your recent booking.
Your table is reserved for {day_instance}/{month_instance}/{year_instance}
at {time_instance} {table_instance}

Kind regards,
The Savory Spot"""

    # Create an EmailMessage instance
    em = EmailMessage()
    em['From'] = email_sender
    em['To'] = email_receiver
    em['Subject'] = subject
    em.set_content(body)

    # Setup SSL context for secure email communication
    context = ssl.create_default_context()

    # If the email receiver is not an empty string, send the email
    if not email_receiver == '':
        with smtplib.SMTP_SSL('smtp.gmail.com', 465, context=context) as smtp:
            smtp.login(email_sender, email_password)
            smtp.sendmail(email_sender, email_receiver, em.as_string())

    # Set a flag in the session to indicate that the reservation was successful
    request.session['reserved'] = True

    # Return the reservation instance
    return reservation


def delete(request, id, email):
    # Retrieve email credentials from environment variables
    email_sender = os.environ.get("email_sender")
    email_password = os.environ.get("email_password")

    # Get the email of the user making the request
    email_receiver = request.user.email

    # Get the reservation instance using the provided id
    reservation_instance = id
    try:
        # Try to get the reservation object with the provided id
        reservation = Reservation.objects.get(id=reservation_instance)

        # Check if the user making the request is the owner of the reservation
        if request.user == reservation.user:
            # Delete the reservation
            reservation.delete()

            # Prepare email content
            subject = 'Reservation'
            body = f"""Hello {request.user}

Your reservation has been canceled.
If you did not perform this action please send us an email on our contact page.

Kind regards,
The Savory Spot"""

            # Create an EmailMessage object
            em = EmailMessage()
            em['From'] = email_sender
            em['To'] = email_receiver
            em['Subject'] = subject
            em.set_content(body)

            # Create an SSL context
            context = ssl.create_default_context()

            # Check if email is provided and the email_receiver is not empty
            if email:
                if not email_receiver == '':
                    # Connect to Gmail SMTP server and send the email
                    with smtplib.SMTP_SSL(
                      'smtp.gmail.com', 465, context=context) as smtp:
                        smtp.login(email_sender, email_password)
                        smtp.sendmail(
                            email_sender, email_receiver, em.as_string())

                    # Set a session variable to indicate successful deletion
                    request.session['deleted'] = True

    except Reservation.DoesNotExist:
        pass


class ReservationView(View):
    template_name = 'reservation.html'

    def get(self, request):
        # Get context for rendering the reservation.html template
        context = get_context(request)
        return render(request, self.template_name, context)

    def post(self, request):
        # Check if the 'submit_reservation' button was clicked
        if 'submit_reservation' in request.POST:
            # Call create function to handle reservation submission
            create(request)
        # Check if the 'delete_reservation' button was clicked
        if 'delete_reservation' in request.POST:
            # Call delete function to handle reservation deletion
            delete(request, request.POST.get('delete_reservation'), True)
        # Redirect to the 'reservation' page after processing the form
        return redirect('reservation')


class EditReservationView(View):
    template_name = 'edit_reservation.html'

    def get(self, request):
        # Get context for rendering the edit_reservation.html template
        context = get_context(request)
        return render(request, self.template_name, context)

    def post(self, request):
        # Check if 'reservation_id' is present in the form data
        if 'reservation_id' in request.POST:
            # Store the reservation_id in the session for later use
            id = request.POST.get('reservation_id')
            request.session['reservation_id'] = id
        # Check if 'edit_reservation' button was clicked
        if 'edit_reservation' in request.POST:
            # Retrieve the reservation_id from the session
            id = request.session.get('reservation_id')
            # Call create function to handle reservation update
            create(request)
            # Check if a new reservation was successfully created
            created = request.session.get('reserved')
            if created:
                # If a new reservation was created, delete the old
                delete(request, id, False)
                return redirect('reservation')
            else:
                return redirect('edit_reservation')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100" lang="en">

<head>
    <!-- Title -->
    <title>The Savory Spot</title>
    <!-- Favicon -->
    <link rel="icon" href="{% static 'images/icon.png' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="View the menu for the restaurant, sign in create reservations and contact us">
    <meta name="keywords" content="restaurant, food, dining, dinner">
    <meta name="author" content="Brian Teahan">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script
        src="https://cdn.jsdelivr.net/npm/@emailjs/browser@3/dist/email.min.js">
    </script>
</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->

    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">The Savoury Spot</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'reservation' %}">Book Reservation</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'contact' %}">Contact Us</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <main>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
    </footer>
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

templates/contact.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-secondary">Send</button>
      </form>
      {% if sent %}
        <div class="alert alert-success mt-3" role="alert">
          Email sent
        </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

templates/edit_reservation.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-12">
                <h2>Edit Reservation:</h2>
                <form method="post" action="{% url 'edit_reservation' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="year">Year:</label>
                        <select name="year" id="year" class="form-control" required>
                            <option value="" disabled selected>Select a year</option>
                            <option value="{{ current_year }}" id="current_year">{{ current_year }}</option>
                            {% for i in "123" %}
                                <option value="{{ current_year|add:forloop.counter }}">{{ current_year|add:forloop.counter }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group" id="current_month_container">
                        <label for="current_month">Month:</label>
                        <select name="current_month" class="form-control month" id="current_month" required>
                            <option value="">Select month</option>
                            <option value="{{current_month}}" id="current_month_value">{{current_month}}</option>
                            {% for month in current_month_range %}
                                <option value="{{ month }}">{{ month }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group" id="month_container" style="display: none;">
                        <label for="month">Month:</label>
                        <select name="month" class="form-control month" id="month">
                            <option value="">Select month</option>
                            {% for month in month_range %}
                                <option value="{{ forloop.counter }}">{{ forloop.counter }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div data-current_value="{{current_day}}" id="current_day_value" style="display: none;"></div>
                    <div class="form-group">
                        <label for="day">Date:</label>
                        <select name="day" id="day" class="form-control" required>
                            <option value="">Select day</option>
                        </select>
                    </div>
                    <div class="form-group" id="current_time_container" style="display: none;">
                        <label for="current_time">Time:</label>
                        <select name="current_time" id="current_time" class="form-control">
                            {% if current_hour > 19 %}
                                {% if current_time > 45 %}
                                    <option value="">Sorry, we are not taking any more bookings for today</option>
                                {% endif %}
                            {% else %} 
                                <option value="">Select a time</option>
                            {% endif %}
                            {% for hour in current_hour_range %}
                                {% if not hour == current_hour %}  
                                    <option value="{{ hour }}:00">{{ hour }}:00</option>
                                {%endif%}
                                {% if hour == current_hour %}
                                    {% if not current_minute > 25%}
                                        <option value="{{ hour }}:30">{{ hour }}:30</option>
                                    {%endif%}
                                {%else%}
                                    <option value="{{ hour }}:30">{{ hour }}:30</option>
                                {%endif%}
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group" id="time_container">
                        <label for="time">Time:</label>
                        <select name="time" id="time" class="form-control" required>
                            <option value="">Select a time</option>
                            {% for hour in time_range %}
                                <option value="{{ hour }}:00">{{ hour }}:00</option>
                                <option value="{{ hour }}:30">{{ hour }}:30</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" name="edit_reservation" class="btn btn-primary">Create Reservation</button>
                </form>
            </div>
        </div>

        {% if reserved %}
            <div class="row mt-3">
                <div class="col-12">
                    <div class="alert alert-success" role="alert">
                        Your reservation has been booked
                    </div>
                </div>
            </div>
        {% endif %}

        {% if booked %}
            <div class="row mt-3">
                <div class="col-12">
                    <div class="alert alert-danger" role="alert">
                        Sorry this time is fully booked out
                    </div>
                </div>
            </div>
        {% endif %}
{% endif %}
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            {% for menu in menu_list %}
                <h1 class="text-center">{{ menu.title }}</h1>
                <input type="text" id="searchInput" class="form-control mb-3" placeholder="Search menu">
                <p>{{ menu.content }}</p>
                <div class="button-container">
                    {% for category in menu.category_set.all %}
                        <button class="category-titles btn btn-primary" data-category="{{category}}">{{ category.title }}</button>
                    {% endfor %}
                </div>
                <div class="item-container mt-3">
                    {% for category in menu.category_set.all %}
                        {% for item in category.item_set.all %}
                            <div class="category-items items card mb-3" style="display: none;" data-category="{{category}}" data-name="{{item.name}}">
                                <div class="card-body">
                                    <h6 class="item item-name card-title">{{ item.name }}</h6>
                                    <p class="item item-description card-text">{{ item.description }}</p>
                                    <p class="item item-price card-text">Price: ${{ item.price }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
  $('#searchInput').on('input', function() {
    var searchTerm = $(this).val().toLowerCase();
    $('.category-items.items').each(function() {
      let itemName = $(this).find('.item:first-child').text().toLowerCase();
      let itemMatches = itemName.indexOf(searchTerm) > -1;
      $(this).toggle(searchTerm === '' ? false : itemMatches);
    });
  });
});
</script>
{%endblock%}